// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvi9_hE3N4LDNBqBI-oYbS74hK7nBwfYQ',
    appId: '1:628962923224:web:ae73bd0a3bb3fe1111bdad',
    messagingSenderId: '628962923224',
    projectId: 'test-fd2f6',
    authDomain: 'test-fd2f6.firebaseapp.com',
    storageBucket: 'test-fd2f6.appspot.com',
    measurementId: 'G-0EMCSXJYX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuereqWaARiKibC2KNyOxBrN1afQWic4Y',
    appId: '1:628962923224:android:ae09a75b8efce64811bdad',
    messagingSenderId: '628962923224',
    projectId: 'test-fd2f6',
    storageBucket: 'test-fd2f6.appspot.com',
  );
}
